import { useEffect, useMemo, useState } from "react";
import { BarChart3, CalendarRange, Download, RefreshCw, TrendingUp } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { canonicalizeFinanceCategory, isPureRentBackPayment, normalizeFinanceCategoryText } from "@/lib/financeCategories";
import { listLoanRatePlanRowsForYear, resolveLoanProperty, type LoanRatePlanRow } from "@/services/loanRatePlanService";
import { useAppData, type AppObject, type FinanceEntry } from "@/state/AppDataContext";

const MONTHS = ["Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"];
const COLORS = ["#0f766e", "#2563eb", "#d97706", "#7c3aed", "#64748b"];
type Preset = "12m" | "year" | "30d" | "24m" | "custom";
const euro = (v: number) => new Intl.NumberFormat("de-DE", { style: "currency", currency: "EUR", minimumFractionDigits: 2 }).format(v || 0);
const iso = (d: Date) => d.toISOString().slice(0, 10);
const monthStart = (d: Date) => new Date(d.getFullYear(), d.getMonth(), 1);
const moveMonths = (d: Date, n: number) => new Date(d.getFullYear(), d.getMonth() + n, 1);
const normalized = (v: unknown) => String(v ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/ß/g, "ss").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
function entryMatches(entry: FinanceEntry, object: AppObject, getName: (id: string | null | undefined) => string) { if (entry.object_id === object.id || entry.objekt_code === object.code) return true; const source = normalized(`${getName(entry.object_id)} ${entry.objekt_code ?? ""}`); return [object.label, object.code, ...(object.aliases ?? [])].filter(Boolean).some((v) => { const key = normalized(v); return key.length > 3 && (source.includes(key) || key.includes(source)); }); }
function loanMatches(row: LoanRatePlanRow, object: AppObject) { if (row.property_id === object.id || row.object_id === object.id || row.objekt_code === object.code) return true; return resolveLoanProperty(object.label)?.key === row.property_key; }
function isRent(entry: FinanceEntry) { if (entry.entry_type !== "income" || isPureRentBackPayment(entry.category, entry.note)) return false; const value = normalizeFinanceCategoryText(canonicalizeFinanceCategory(entry.category, "income")); return value === "miete" || value === "miete garage" || value.includes("mieteinnahme"); }
function expenseBucket(entry: FinanceEntry) { const v = normalizeFinanceCategoryText(`${entry.category ?? ""} ${entry.note ?? ""}`); if (v.includes("grundsteuer")) return "Grundsteuer"; if (v.includes("verwaltung")) return "Verwaltungskosten"; if (v.includes("versicherung")) return "Versicherungen"; if (v.includes("abfall") || v.includes("mull") || v.includes("muell")) return "Abfallgebühren"; return "Sonstiges"; }
function saveCsv(name: string, rows: Array<Array<string | number>>) { const body = rows.map((row) => row.map((v) => `"${String(v).replaceAll('"', '""')}"`).join(";")).join("\n"); const url = URL.createObjectURL(new Blob([`\uFEFF${body}`], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }
function ChartCard({ title, text, actions, children }: { title: string; text: string; actions?: React.ReactNode; children: React.ReactNode }) { return <section className="min-w-0 rounded-[24px] border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><h2 className="text-xl font-black text-slate-950">{title}</h2><p className="mt-1 text-sm font-semibold leading-6 text-slate-500">{text}</p></div>{actions}</div><div className="mt-5 min-w-0">{children}</div></section>; }

export default function WealthCashflowDashboard() {
  const { objects, entries, getPropertyName, loading } = useAppData();
  const today = useMemo(() => new Date(), []); const currentYear = today.getFullYear();
  const [year, setYear] = useState(currentYear); const [propertyId, setPropertyId] = useState("all"); const [preset, setPreset] = useState<Preset>("year");
  const [from, setFrom] = useState(`${currentYear}-01-01`); const [to, setTo] = useState(`${currentYear}-12-31`);
  const [loans, setLoans] = useState<LoanRatePlanRow[]>([]); const [loanError, setLoanError] = useState<string | null>(null); const [loanLoading, setLoanLoading] = useState(true);
  const range = useMemo(() => { if (preset === "custom") return { start: from, end: to, label: `${from} bis ${to}` }; if (preset === "30d") { const d = new Date(today); d.setDate(d.getDate() - 29); return { start: iso(d), end: iso(today), label: "Letzte 30 Tage" }; } if (preset === "12m") return { start: iso(moveMonths(monthStart(today), -11)), end: iso(today), label: "Letzte 12 Monate" }; if (preset === "24m") return { start: iso(moveMonths(monthStart(today), -23)), end: iso(today), label: "Letzte 24 Monate" }; return { start: `${year}-01-01`, end: `${year}-12-31`, label: `Kalenderjahr ${year}` }; }, [from, preset, to, today, year]);
  const rangeYears = useMemo(() => { const first = Number(range.start.slice(0, 4)); const last = Number(range.end.slice(0, 4)); return Array.from({ length: Math.max(1, last - first + 1) }, (_, i) => first + i); }, [range.end, range.start]);
  const years = useMemo(() => Array.from(new Set([currentYear, ...entries.map((e) => Number(e.booking_date?.slice(0, 4))).filter(Number.isFinite)])).sort((a, b) => b - a), [currentYear, entries]);
  const object = objects.find((o) => o.id === propertyId) ?? null;
  async function reload() { setLoanLoading(true); try { setLoans((await Promise.all(rangeYears.map(listLoanRatePlanRowsForYear))).flat()); setLoanError(null); } catch (e) { setLoans([]); setLoanError(e instanceof Error ? e.message : String(e)); } finally { setLoanLoading(false); } }
  useEffect(() => { let active = true; Promise.all(rangeYears.map(listLoanRatePlanRowsForYear)).then((r) => { if (active) { setLoans(r.flat()); setLoanError(null); } }).catch((e) => { if (active) { setLoans([]); setLoanError(e instanceof Error ? e.message : String(e)); } }).finally(() => { if (active) setLoanLoading(false); }); return () => { active = false; }; }, [rangeYears]);
  const scopedEntries = useMemo(() => entries.filter((e) => Boolean(e.booking_date && e.booking_date >= range.start && e.booking_date <= range.end) && (!object || entryMatches(e, object, getPropertyName))), [entries, getPropertyName, object, range.end, range.start]);
  const scopedLoans = useMemo(() => loans.filter((r) => r.plan_date >= range.start && r.plan_date <= range.end && (!object || loanMatches(r, object))), [loans, object, range.end, range.start]);
  const monthKeys = useMemo(() => { const result: string[] = []; let d = monthStart(new Date(`${range.start}T00:00:00`)); const end = monthStart(new Date(`${range.end}T00:00:00`)); while (d <= end && result.length < 24) { result.push(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`); d = moveMonths(d, 1); } return result; }, [range.end, range.start]);
  const monthly = useMemo(() => monthKeys.map((key) => { const monthEntries = scopedEntries.filter((e) => e.booking_date?.startsWith(key)); const income = monthEntries.filter((e) => e.entry_type === "income").reduce((s, e) => s + Math.abs(e.amount), 0); const expenses = monthEntries.filter((e) => e.entry_type === "expense").reduce((s, e) => s + Math.abs(e.amount), 0); const rent = monthEntries.filter(isRent).reduce((s, e) => s + Math.abs(e.amount), 0); const annuity = scopedLoans.filter((r) => r.plan_date.startsWith(key)).reduce((s, r) => s + Math.abs(Number(r.payment_amount || 0)), 0); return { key, month: `${MONTHS[Number(key.slice(5, 7)) - 1]}${monthKeys.length > 12 ? ` ${key.slice(2, 4)}` : ""}`, income, expenses, cashflow: income - expenses, rent, annuity, surplus: rent - annuity }; }), [monthKeys, scopedEntries, scopedLoans]);
  const comparisonRows = [['Annuität','annuity'],['Mieteinnahmen','rent'],['Überschuss','surplus']] as const;
  const cumulative = useMemo(() => monthly.reduce<Array<{ month: string; value: number }>>((rows, r) => [...rows, { month: r.month, value: (rows.at(-1)?.value ?? 0) + r.cashflow }], []), [monthly]);
  const expenseData = useMemo(() => { const totals = new Map<string, number>(); scopedEntries.filter((e) => e.entry_type === "expense").forEach((e) => totals.set(expenseBucket(e), (totals.get(expenseBucket(e)) ?? 0) + Math.abs(e.amount))); return Array.from(totals, ([name, value]) => ({ name, value })); }, [scopedEntries]);
  const filters = <div className="grid gap-2 sm:grid-cols-2"><select aria-label="Immobilie" value={propertyId} onChange={(e) => setPropertyId(e.target.value)} className="min-h-11 min-w-0 rounded-xl border border-slate-200 bg-white px-3 text-sm font-black"><option value="all">Alle Immobilien</option>{objects.map((o) => <option key={o.id} value={o.id}>{o.label}</option>)}</select><select aria-label="Jahr" value={year} onChange={(e) => { setYear(Number(e.target.value)); setPreset("year"); }} className="min-h-11 min-w-0 rounded-xl border border-slate-200 bg-white px-3 text-sm font-black">{years.map((v) => <option key={v}>{v}</option>)}</select></div>;
  const exportRows = () => saveCsv(`vermoegen-cashflow-${range.start}-${range.end}.csv`, [["Zeitraum", range.label], ["Immobilie", object?.label ?? "Alle Immobilien"], [], ["Monat", "Einnahmen", "Ausgaben", "Netto-Cashflow", "Mieteinnahmen", "Annuität", "Überschuss"], ...monthly.map((r) => [r.key, r.income.toFixed(2), r.expenses.toFixed(2), r.cashflow.toFixed(2), r.rent.toFixed(2), r.annuity.toFixed(2), r.surplus.toFixed(2)])]);
  return <div className="mx-auto max-w-[1760px] space-y-5">
    <section className="rounded-[26px] border border-slate-200 bg-white p-4 shadow-sm sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full bg-teal-50 px-3 py-1 text-xs font-black uppercase tracking-[.12em] text-teal-800"><TrendingUp size={15}/> Cockpit</div><h1 className="mt-4 text-2xl font-black sm:text-3xl">Vermögensübersicht & Cashflow-Dashboard</h1><p className="mt-2 max-w-4xl text-sm font-semibold leading-6 text-slate-600">Ist-Buchungen und importierte Darlehens-Tilgungspläne werden live aggregiert. Es gibt keine zweite Report-Datenquelle.</p></div><div className="grid gap-2 sm:grid-cols-2"><button type="button" onClick={() => void reload()} disabled={loanLoading} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-black"><RefreshCw size={16}/> Aktualisieren</button><button type="button" onClick={exportRows} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 text-sm font-black text-white"><Download size={16}/> Export</button></div></div><div className="mt-5 border-t border-slate-100 pt-4"><div className="flex flex-wrap gap-2">{([['12m','12 Monate'],['year','Dieses Jahr'],['30d','30 Tage'],['24m','24 Monate'],['custom','Zeitraum']] as const).map(([key, label]) => <button key={key} type="button" onClick={() => setPreset(key)} className={`min-h-10 rounded-xl px-4 text-sm font-black ${preset === key ? "bg-[#255f6f] text-white" : "border border-slate-200 bg-white text-slate-700"}`}>{label}</button>)}</div>{preset === "custom" ? <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:max-w-xl"><label className="grid gap-1 text-xs font-black uppercase text-slate-500">Von<input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="min-h-11 rounded-xl border border-slate-200 px-3 text-sm text-slate-950"/></label><label className="grid gap-1 text-xs font-black uppercase text-slate-500">Bis<input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="min-h-11 rounded-xl border border-slate-200 px-3 text-sm text-slate-950"/></label></div> : null}<p className="mt-3 inline-flex items-center gap-2 text-sm font-bold text-slate-500"><CalendarRange size={16}/>{range.label}</p></div></section>
    {loanError ? <div role="alert" className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-900">Darlehens-Tilgungspläne konnten nicht geladen werden: {loanError}</div> : null}
    <ChartCard title="Mieteinnahmen vs. Kreditrate" text="Soll-/Ist-Vergleich aus Buchungen und Darlehens-Tilgungsplan." actions={filters}><div className="h-[320px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={monthly}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis tickFormatter={(v) => `${Math.round(v / 1000)} T€`}/><Tooltip formatter={(v) => euro(Number(v))}/><Legend/><Bar dataKey="rent" name="Mieteinnahmen" fill="#0f766e"/><Bar dataKey="annuity" name="Annuität" fill="#d97706"/></BarChart></ResponsiveContainer></div><div className="mt-4 grid gap-2 sm:grid-cols-3">{comparisonRows.map(([label, key]) => <div key={key} className="rounded-2xl border border-slate-200 bg-slate-50 p-3"><span className="text-xs font-black uppercase tracking-wide text-slate-500">{label}</span><strong className="mt-1 block text-right text-lg tabular-nums">{euro(monthly.reduce((sum, row) => sum + row[key], 0))}</strong></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{monthly.map((r) => <div key={r.key} className="rounded-2xl border border-slate-200 p-3"><b>{r.month}</b><div className="mt-2 grid grid-cols-2 gap-1 text-xs"><span>Miete</span><strong className="text-right tabular-nums">{euro(r.rent)}</strong><span>Annuität</span><strong className="text-right tabular-nums">{euro(r.annuity)}</strong><span>Überschuss</span><strong className="text-right tabular-nums">{euro(r.surplus)}</strong></div></div>)}</div></ChartCard>
    <ChartCard title="Cashflow-Detailansicht" text="Einnahmen, Ausgaben und tatsächlicher Netto-Cashflow pro Monat." actions={filters}><div className="h-[340px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={monthly}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis tickFormatter={(v) => `${Math.round(v / 1000)} T€`}/><Tooltip formatter={(v) => euro(Number(v))}/><Legend/><Bar dataKey="income" name="Einnahmen" fill="#059669"/><Bar dataKey="expenses" name="Ausgaben" fill="#dc2626"/><Bar dataKey="cashflow" name="Cashflow" fill="#2563eb"/></BarChart></ResponsiveContainer></div></ChartCard>
    <div className="grid gap-5 xl:grid-cols-2"><ChartCard title="Kumulierter Cashflow" text="Fortlaufender Saldo im gewählten Zeitraum." actions={filters}><div className="h-[320px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={cumulative}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis tickFormatter={(v) => `${Math.round(v / 1000)} T€`}/><Tooltip formatter={(v) => euro(Number(v))}/><Line type="monotone" dataKey="value" name="Kumulierter Cashflow" stroke="#0f766e" strokeWidth={3}/></LineChart></ResponsiveContainer></div></ChartCard><ChartCard title="Ausgabenverteilung" text="Grundsteuer, Verwaltung, Versicherungen, Abfall und sonstige Ausgaben." actions={filters}><div className="h-[320px]">{expenseData.length ? <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={expenseData} dataKey="value" nameKey="name" outerRadius={95} label={({ name }) => name}>{expenseData.map((r, i) => <Cell key={r.name} fill={COLORS[i % COLORS.length]}/>)}</Pie><Tooltip formatter={(v) => euro(Number(v))}/><Legend/></PieChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center rounded-2xl bg-slate-50 text-sm font-bold text-slate-500">Keine Ausgaben im gewählten Zeitraum.</div>}</div></ChartCard></div>
    {(loading || loanLoading) ? <div className="text-center text-sm font-bold text-slate-500"><BarChart3 className="mr-2 inline" size={16}/>Daten werden aktualisiert…</div> : null}
  </div>;
}
